export const routes = {
  HOME: "/",
  ADMIN: "/admin",
  ADMIN_INGREDIENTS: "/admin/ingredients",
  ADMIN_PRODUCTS: "/admin/products",
  DASHBOARD: "/dashboard",
  ONBOARDING_SKIN_PROFILE: "/onboarding/skin-profile",
  ROUTINES: "/routines",
  TODAY_LOG: "/routine-logs/today",
  JOURNAL: "/journal",
  PRODUCTS: "/products",
  PRODUCT_MATCH: "/product-match",
  SAVED_PRODUCTS: "/saved-products",
  INSIGHTS: "/insights",
  INGREDIENTS: "/ingredients",
  SETTINGS: "/settings",
  SKIN_PROFILE: "/skin-profile",
} as const;
