import { pathToFileURL } from "node:url";

import type { BulkWriteResult, Collection } from "mongodb";
import { z } from "zod";

import type { IngredientDocument } from "@/modules/ingredients/ingredient.types";
import { INGREDIENT_EVIDENCE_LEVELS } from "@/modules/ingredients/ingredient.types";
import {
  PRODUCT_CATEGORIES,
  PRODUCT_CONCERNS,
  PRODUCT_PRICE_RANGES,
  PRODUCT_SOURCES,
  PRODUCT_SKIN_TYPES,
  VISIBLE_PRODUCT_VERIFICATION_STATUSES,
  type ProductDocument,
} from "@/modules/products/product.types";

type IngredientSeed = Omit<IngredientDocument, "createdAt" | "updatedAt">;
type ProductSeed = Omit<
  ProductDocument,
  "createdAt" | "createdByUserId" | "updatedAt"
> & {
  source: "manual";
  verificationStatus: (typeof VISIBLE_PRODUCT_VERIFICATION_STATUSES)[number];
};

type SeedWriteSummary = {
  matchedCount: number;
  modifiedCount: number;
  upsertedCount: number;
};

const MANUAL_PRODUCT_SOURCE = PRODUCT_SOURCES[0];
const MINIMUM_V1_24_INGREDIENT_COUNT = 70;
const MINIMUM_V1_24_PRODUCT_COUNT = 70;
const stringListSchema = z.array(z.string().trim().min(1));

const ingredientSeedSchema = z
  .object({
    inciName: z.string().trim().min(1).max(160),
    aliases: stringListSchema,
    functions: stringListSchema,
    commonUses: stringListSchema,
    suitableFor: stringListSchema,
    cautionFor: stringListSchema,
    avoidWith: stringListSchema,
    evidenceLevel: z.enum(INGREDIENT_EVIDENCE_LEVELS),
    sourceRefs: stringListSchema,
  })
  .strict();

const productSeedSchema = z
  .object({
    name: z.string().trim().min(1).max(160),
    brand: z.string().trim().min(1).max(100),
    category: z.enum(PRODUCT_CATEGORIES),
    priceRange: z.enum(PRODUCT_PRICE_RANGES),
    ingredientsText: z.string().trim().min(1).max(5000),
    keyActives: stringListSchema,
    tags: stringListSchema,
    warnings: z.array(z.string().trim().min(1)),
    skinTypes: z.array(z.enum(PRODUCT_SKIN_TYPES)).min(1),
    concerns: z.array(z.enum(PRODUCT_CONCERNS)).min(1),
    suitableFor: stringListSchema,
    notRecommendedFor: stringListSchema,
    source: z.literal(MANUAL_PRODUCT_SOURCE),
    verificationStatus: z.enum(VISIBLE_PRODUCT_VERIFICATION_STATUSES),
  })
  .strict();

const requiredProductCategories = [
  "cleanser",
  "moisturizer",
  "sunscreen",
  "treatment",
  "toner",
  "serum",
  "mask",
  "other",
] as const;
const requiredProductSkinTypes = [
  "oily",
  "dry",
  "combination",
  "normal",
  "sensitive",
  "unknown",
] as const;
const requiredProductConcerns = [
  "acne",
  "oiliness",
  "dryness",
  "redness",
  "dark_spots",
  "texture",
  "barrier_support",
  "unknown",
] as const;
const strongActiveTerms = [
  "aha",
  "bha",
  "retinol",
  "retinal",
  "retinoid",
  "adapalene",
  "benzoyl peroxide",
  "salicylic acid",
  "glycolic acid",
  "lactic acid",
  "mandelic acid",
  "gluconolactone",
  "lactobionic acid",
  "kojic acid",
  "tea tree oil",
  "sulfur",
  "vitamin c",
  "ascorbic acid",
] as const;
const requiredStrongActiveIngredients = [
  "Salicylic Acid",
  "Benzoyl Peroxide",
  "Sulfur",
  "Tea Tree Oil",
  "Retinol",
  "Retinal",
  "Adapalene",
  "Glycolic Acid",
  "Lactic Acid",
  "Mandelic Acid",
  "Gluconolactone",
  "Lactobionic Acid",
  "Kojic Acid",
  "Vitamin C",
  "Sodium Ascorbyl Phosphate",
] as const;

function assertSeedCondition(condition: boolean, message: string) {
  if (!condition) {
    throw new Error(message);
  }
}

function normalizeSeedText(value: string) {
  return value.toLowerCase();
}

function productSearchText(product: ProductSeed) {
  return normalizeSeedText(
    [
      product.name,
      product.brand,
      product.ingredientsText,
      ...product.keyActives,
      ...product.tags,
      ...product.warnings,
      ...product.suitableFor,
      ...product.notRecommendedFor,
    ].join(" "),
  );
}

function assertUniqueValues(values: string[], message: string) {
  const seen = new Set<string>();

  for (const value of values) {
    const normalizedValue = normalizeSeedText(value.trim());

    assertSeedCondition(!seen.has(normalizedValue), `${message}: ${value}`);
    seen.add(normalizedValue);
  }
}

function assertEveryRequiredValue<TValue extends string>(
  actualValues: readonly TValue[],
  requiredValues: readonly TValue[],
  label: string,
) {
  const actual = new Set(actualValues);

  for (const requiredValue of requiredValues) {
    assertSeedCondition(
      actual.has(requiredValue),
      `Seed data must cover ${label}: ${requiredValue}`,
    );
  }
}

function assertProductTextIncludes(
  products: ProductSeed[],
  aliases: string[],
  message: string,
) {
  const productTexts = products.map(productSearchText);

  for (const alias of aliases) {
    const normalizedAlias = normalizeSeedText(alias);

    assertSeedCondition(
      productTexts.some((text) => text.includes(normalizedAlias)),
      `${message}: ${alias}`,
    );
  }
}

function containsAnySeedTerm(text: string, terms: readonly string[]) {
  const normalizedText = normalizeSeedText(text);

  return terms.some((term) => normalizedText.includes(term));
}

function assertStrongActiveProductWarnings(products: ProductSeed[]) {
  for (const product of products) {
    const activeText = [
      product.ingredientsText,
      ...product.keyActives,
      ...product.tags,
    ].join(" ");

    if (containsAnySeedTerm(activeText, strongActiveTerms)) {
      assertSeedCondition(
        product.warnings.length > 0,
        `Strong active product must include a caution warning: ${product.brand} ${product.name}`,
      );
    }
  }
}

function assertStrongActiveIngredientCautions(ingredients: IngredientSeed[]) {
  const ingredientsByName = new Map(
    ingredients.map((ingredient) => [ingredient.inciName, ingredient]),
  );

  for (const ingredientName of requiredStrongActiveIngredients) {
    const ingredient = ingredientsByName.get(ingredientName);

    assertSeedCondition(
      Boolean(ingredient),
      `Seed data must include strong active ingredient: ${ingredientName}`,
    );
    assertSeedCondition(
      (ingredient?.cautionFor.length ?? 0) > 0,
      `Strong active ingredient must include cautionFor: ${ingredientName}`,
    );
  }
}

export function validateSeedData() {
  const seedData = {
    ingredients: z.array(ingredientSeedSchema).parse(ingredientSeeds),
    products: z.array(productSeedSchema).parse(productSeeds),
  };

  assertSeedQuality(seedData);

  return seedData;
}

function assertSeedQuality(input: {
  ingredients: IngredientSeed[];
  products: ProductSeed[];
}) {
  const { ingredients, products } = input;

  assertSeedCondition(
    ingredients.length >= MINIMUM_V1_24_INGREDIENT_COUNT,
    `Seed data must include at least ${MINIMUM_V1_24_INGREDIENT_COUNT} ingredients for the v1.24 baseline.`,
  );
  assertSeedCondition(
    products.length >= MINIMUM_V1_24_PRODUCT_COUNT,
    `Seed data must include at least ${MINIMUM_V1_24_PRODUCT_COUNT} products for the v1.24 baseline.`,
  );
  assertUniqueValues(
    ingredients.map((ingredient) => ingredient.inciName),
    "Duplicate ingredient inciName",
  );
  assertUniqueValues(
    ingredients.flatMap((ingredient) => ingredient.aliases),
    "Duplicate ingredient alias",
  );
  assertUniqueValues(
    products.map((product) => product.name),
    "Duplicate product name",
  );
  assertUniqueValues(
    products.map((product) => `${product.brand}::${product.name}`),
    "Duplicate product brand/name pair",
  );
  assertEveryRequiredValue(
    products.map((product) => product.category),
    requiredProductCategories,
    "product category",
  );
  assertEveryRequiredValue(
    products.flatMap((product) => product.skinTypes),
    requiredProductSkinTypes,
    "skin type",
  );
  assertEveryRequiredValue(
    products.flatMap((product) => product.concerns),
    requiredProductConcerns,
    "skin concern",
  );
  assertProductTextIncludes(
    products,
    ["sunscreen"],
    "Seed data must support missing-sunscreen demos",
  );
  assertProductTextIncludes(
    products,
    ["mandelic acid", "salicylic acid", "retinol", "benzoyl peroxide"],
    "Seed data must support active-conflict demos",
  );
  assertProductTextIncludes(
    products,
    ["fragrance", "parfum", "essential oil blend"],
    "Seed data must support sensitive-skin fragrance caution demos",
  );
  assertProductTextIncludes(
    products,
    ["ceramide", "panthenol", "glycerin", "cholesterol", "fatty acids", "squalane"],
    "Seed data must support barrier-recovery demos",
  );
  assertProductTextIncludes(
    products,
    ["azelaic acid", "vitamin c", "tranexamic acid", "alpha arbutin", "niacinamide"],
    "Seed data must support uneven-tone demo coverage",
  );
  assertStrongActiveProductWarnings(products);
  assertStrongActiveIngredientCautions(ingredients);
}

const ingredientSeeds = [
  {
    inciName: "Niacinamide",
    aliases: ["Vitamin B3", "Nicotinamide"],
    functions: ["barrier_support", "oil_balance", "active"],
    commonUses: ["oiliness support", "barrier support", "tone support"],
    suitableFor: ["oily", "combination", "normal", "barrier_support"],
    cautionFor: ["very sensitive skin", "recently irritated skin"],
    avoidWith: [],
    evidenceLevel: "moderate",
    sourceRefs: ["manual-curation"],
  },
  {
    inciName: "Salicylic Acid",
    aliases: ["BHA", "Beta Hydroxy Acid"],
    functions: ["exfoliant", "oil_balance", "active"],
    commonUses: ["clogged-pore support", "surface exfoliation"],
    suitableFor: ["oily", "combination", "acne"],
    cautionFor: ["sensitive skin", "dry skin", "over-exfoliated skin"],
    avoidWith: ["retinoids in the same routine", "other strong exfoliants"],
    evidenceLevel: "strong",
    sourceRefs: ["manual-curation"],
  },
  {
    inciName: "Azelaic Acid",
    aliases: ["Azelaic Acid"],
    functions: ["active", "texture_support", "redness_support"],
    commonUses: ["tone support", "redness-prone skin support"],
    suitableFor: ["oily", "combination", "redness", "dark_spots"],
    cautionFor: ["very sensitive skin", "recently irritated skin"],
    avoidWith: ["too many strong actives in one routine"],
    evidenceLevel: "moderate",
    sourceRefs: ["manual-curation"],
  },
  {
    inciName: "Retinol",
    aliases: ["Vitamin A"],
    functions: ["retinoid", "active", "texture_support"],
    commonUses: ["texture support", "signs-of-aging support"],
    suitableFor: ["normal", "combination", "texture"],
    cautionFor: ["beginners", "sensitive skin", "pregnancy or breastfeeding"],
    avoidWith: ["AHA/BHA in the same routine", "benzoyl peroxide"],
    evidenceLevel: "strong",
    sourceRefs: ["manual-curation"],
  },
  {
    inciName: "Hyaluronic Acid",
    aliases: ["Sodium Hyaluronate", "HA"],
    functions: ["humectant", "hydration_support"],
    commonUses: ["hydration support", "layering under moisturizer"],
    suitableFor: ["dry", "normal", "combination", "barrier_support"],
    cautionFor: ["very dry climates without moisturizer"],
    avoidWith: [],
    evidenceLevel: "moderate",
    sourceRefs: ["manual-curation"],
  },
  {
    inciName: "Glycerin",
    aliases: ["Glycerol"],
    functions: ["humectant", "hydration_support"],
    commonUses: ["hydration support", "cleanser and moisturizer support"],
    suitableFor: ["oily", "combination", "dry", "sensitive"],
    cautionFor: ["known sensitivity to the product formula"],
    avoidWith: [],
    evidenceLevel: "strong",
    sourceRefs: ["manual-curation"],
  },
  {
    inciName: "Ceramide NP",
    aliases: ["Ceramide 3", "Ceramide"],
    functions: ["barrier_support", "emollient"],
    commonUses: ["barrier support", "moisturizer support"],
    suitableFor: ["dry", "sensitive", "barrier_support"],
    cautionFor: ["known sensitivity to the product formula"],
    avoidWith: [],
    evidenceLevel: "moderate",
    sourceRefs: ["manual-curation"],
  },
  {
    inciName: "Panthenol",
    aliases: ["Pro-Vitamin B5", "Dexpanthenol"],
    functions: ["soothing_support", "humectant", "barrier_support"],
    commonUses: ["comfort support", "hydration support"],
    suitableFor: ["dry", "sensitive", "barrier_support", "redness"],
    cautionFor: ["known sensitivity to the product formula"],
    avoidWith: [],
    evidenceLevel: "moderate",
    sourceRefs: ["manual-curation"],
  },
  {
    inciName: "Benzoyl Peroxide",
    aliases: ["BPO"],
    functions: ["active", "blemish_support"],
    commonUses: ["spot-care support", "blemish-prone routine support"],
    suitableFor: ["oily", "acne"],
    cautionFor: ["dry skin", "sensitive skin", "recently irritated skin"],
    avoidWith: ["retinoids in the same routine", "strong exfoliants"],
    evidenceLevel: "strong",
    sourceRefs: ["manual-curation"],
  },
  {
    inciName: "Vitamin C",
    aliases: ["Ascorbic Acid", "Ascorbyl Glucoside"],
    functions: ["antioxidant", "tone_support", "active"],
    commonUses: ["antioxidant support", "dullness support"],
    suitableFor: ["normal", "combination", "dark_spots"],
    cautionFor: ["sensitive skin", "recently irritated skin"],
    avoidWith: ["too many strong actives in one routine"],
    evidenceLevel: "moderate",
    sourceRefs: ["manual-curation"],
  },
  {
    inciName: "Centella Asiatica Extract",
    aliases: ["Centella Asiatica", "Cica", "Gotu Kola"],
    functions: ["soothing_support", "barrier_support"],
    commonUses: ["comfort support", "redness-prone skin support"],
    suitableFor: ["sensitive", "redness", "barrier_support"],
    cautionFor: ["known sensitivity to botanical extracts"],
    avoidWith: [],
    evidenceLevel: "basic",
    sourceRefs: ["manual-curation"],
  },
  {
    inciName: "Green Tea Extract",
    aliases: ["Camellia Sinensis Leaf Extract"],
    functions: ["antioxidant", "soothing_support", "skin_conditioning"],
    commonUses: ["comfort support", "oiliness-prone routine support"],
    suitableFor: ["oily", "combination", "redness"],
    cautionFor: ["known sensitivity to botanical extracts"],
    avoidWith: [],
    evidenceLevel: "basic",
    sourceRefs: ["manual-curation"],
  },
  {
    inciName: "Glycolic Acid",
    aliases: ["Glycolic Acid AHA"],
    functions: ["exfoliant", "texture_support", "active"],
    commonUses: ["surface exfoliation", "texture support"],
    suitableFor: ["normal", "combination", "texture"],
    cautionFor: ["sensitive skin", "dry skin", "sun-sensitive routines"],
    avoidWith: ["retinoids in the same routine", "other strong exfoliants"],
    evidenceLevel: "strong",
    sourceRefs: ["manual-curation"],
  },
  {
    inciName: "Lactic Acid",
    aliases: ["Lactic Acid AHA"],
    functions: ["exfoliant", "humectant", "active"],
    commonUses: ["gentler exfoliation support", "texture support"],
    suitableFor: ["normal", "dry", "texture"],
    cautionFor: ["sensitive skin", "over-exfoliated skin"],
    avoidWith: ["retinoids in the same routine", "other strong exfoliants"],
    evidenceLevel: "moderate",
    sourceRefs: ["manual-curation"],
  },
  {
    inciName: "Zinc PCA",
    aliases: ["Zinc Pyrrolidone Carboxylic Acid"],
    functions: ["oil_balance", "skin_conditioning"],
    commonUses: ["oiliness support", "lightweight serum support"],
    suitableFor: ["oily", "combination", "oiliness"],
    cautionFor: ["very dry skin"],
    avoidWith: [],
    evidenceLevel: "basic",
    sourceRefs: ["manual-curation"],
  },
  {
    inciName: "Cholesterol",
    aliases: ["Skin-identical lipid"],
    functions: ["barrier_support", "emollient"],
    commonUses: ["barrier support", "comfort support"],
    suitableFor: ["dry", "sensitive", "barrier_support"],
    cautionFor: ["known sensitivity to the product formula"],
    avoidWith: [],
    evidenceLevel: "moderate",
    sourceRefs: ["manual-curation"],
  },
  {
    inciName: "Fatty Acids",
    aliases: ["Linoleic Acid", "Stearic Acid"],
    functions: ["barrier_support", "emollient"],
    commonUses: ["barrier support", "dryness support"],
    suitableFor: ["dry", "normal", "barrier_support"],
    cautionFor: ["known sensitivity to richer textures"],
    avoidWith: [],
    evidenceLevel: "basic",
    sourceRefs: ["manual-curation"],
  },
  {
    inciName: "Squalane",
    aliases: ["Hydrogenated Squalene"],
    functions: ["emollient", "texture_support"],
    commonUses: ["lightweight emollient support", "moisturizer support"],
    suitableFor: ["dry", "normal", "combination", "barrier_support"],
    cautionFor: ["users who dislike oil-like textures"],
    avoidWith: [],
    evidenceLevel: "basic",
    sourceRefs: ["manual-curation"],
  },
  {
    inciName: "Betaine",
    aliases: ["Trimethylglycine"],
    functions: ["humectant", "hydration_support"],
    commonUses: ["hydration support", "comfort support"],
    suitableFor: ["dry", "normal", "combination", "sensitive"],
    cautionFor: ["known sensitivity to the product formula"],
    avoidWith: [],
    evidenceLevel: "basic",
    sourceRefs: ["manual-curation"],
  },
  {
    inciName: "Urea",
    aliases: ["Carbamide"],
    functions: ["humectant", "texture_support"],
    commonUses: ["dryness support", "rough texture support"],
    suitableFor: ["dry", "texture"],
    cautionFor: ["stinging on cracked or recently irritated skin"],
    avoidWith: ["too many exfoliating products in one routine"],
    evidenceLevel: "moderate",
    sourceRefs: ["manual-curation"],
  },
  {
    inciName: "Sodium PCA",
    aliases: ["PCA Sodium"],
    functions: ["humectant", "hydration_support"],
    commonUses: ["hydration support", "lightweight serum support"],
    suitableFor: ["oily", "combination", "dry", "normal"],
    cautionFor: ["known sensitivity to the product formula"],
    avoidWith: [],
    evidenceLevel: "basic",
    sourceRefs: ["manual-curation"],
  },
  {
    inciName: "Sulfur",
    aliases: ["Sulphur"],
    functions: ["active", "oil_balance"],
    commonUses: ["oiliness support", "blemish-prone routine support"],
    suitableFor: ["oily", "acne"],
    cautionFor: ["dry skin", "sensitive skin", "recently irritated skin"],
    avoidWith: ["other drying spot-care products in the same routine"],
    evidenceLevel: "moderate",
    sourceRefs: ["manual-curation"],
  },
  {
    inciName: "Mandelic Acid",
    aliases: ["Mandelic Acid AHA"],
    functions: ["exfoliant", "texture_support", "active"],
    commonUses: ["gentle exfoliation support", "uneven texture support"],
    suitableFor: ["normal", "combination", "texture"],
    cautionFor: ["sensitive skin", "recently irritated skin", "over-exfoliated skin"],
    avoidWith: ["retinoids in the same routine", "other strong exfoliants"],
    evidenceLevel: "moderate",
    sourceRefs: ["manual-curation"],
  },
  {
    inciName: "Gluconolactone",
    aliases: ["PHA", "Polyhydroxy Acid"],
    functions: ["exfoliant", "humectant", "texture_support"],
    commonUses: ["mild exfoliation support", "hydration-supporting exfoliant"],
    suitableFor: ["dry", "sensitive", "texture"],
    cautionFor: ["recently irritated skin", "over-exfoliated skin"],
    avoidWith: ["too many exfoliants in one routine"],
    evidenceLevel: "basic",
    sourceRefs: ["manual-curation"],
  },
  {
    inciName: "Retinal",
    aliases: ["Retinaldehyde"],
    functions: ["retinoid", "active", "texture_support"],
    commonUses: ["texture support", "advanced evening routine support"],
    suitableFor: ["normal", "combination", "texture"],
    cautionFor: ["beginners", "sensitive skin", "pregnancy or breastfeeding"],
    avoidWith: ["AHA/BHA in the same routine", "benzoyl peroxide"],
    evidenceLevel: "moderate",
    sourceRefs: ["manual-curation"],
  },
  {
    inciName: "Adapalene",
    aliases: ["Adapalene retinoid"],
    functions: ["retinoid", "active"],
    commonUses: ["blemish-prone routine support", "texture support"],
    suitableFor: ["oily", "acne", "texture"],
    cautionFor: ["beginners", "dry skin", "sensitive skin", "pregnancy or breastfeeding"],
    avoidWith: ["AHA/BHA in the same routine", "benzoyl peroxide without guidance"],
    evidenceLevel: "strong",
    sourceRefs: ["manual-curation"],
  },
  {
    inciName: "Tranexamic Acid",
    aliases: ["TXA"],
    functions: ["tone_support", "active"],
    commonUses: ["uneven tone support", "dark-spot routine support"],
    suitableFor: ["normal", "combination", "dark_spots"],
    cautionFor: ["very sensitive skin", "recently irritated skin"],
    avoidWith: ["too many strong actives in one routine"],
    evidenceLevel: "moderate",
    sourceRefs: ["manual-curation"],
  },
  {
    inciName: "Alpha Arbutin",
    aliases: ["Arbutin"],
    functions: ["tone_support", "active"],
    commonUses: ["uneven tone support", "dark-spot routine support"],
    suitableFor: ["normal", "combination", "dark_spots"],
    cautionFor: ["very sensitive skin", "recently irritated skin"],
    avoidWith: [],
    evidenceLevel: "basic",
    sourceRefs: ["manual-curation"],
  },
  {
    inciName: "Licorice Root Extract",
    aliases: ["Glycyrrhiza Glabra Root Extract"],
    functions: ["soothing_support", "tone_support", "botanical_extract"],
    commonUses: ["comfort support", "uneven tone support"],
    suitableFor: ["sensitive", "redness", "dark_spots"],
    cautionFor: ["known sensitivity to botanical extracts"],
    avoidWith: [],
    evidenceLevel: "basic",
    sourceRefs: ["manual-curation"],
  },
  {
    inciName: "Madecassoside",
    aliases: ["Centella component"],
    functions: ["soothing_support", "barrier_support"],
    commonUses: ["comfort support", "redness-prone skin support"],
    suitableFor: ["sensitive", "redness", "barrier_support"],
    cautionFor: ["known sensitivity to the product formula"],
    avoidWith: [],
    evidenceLevel: "basic",
    sourceRefs: ["manual-curation"],
  },
  {
    inciName: "Allantoin",
    aliases: ["Aluminum Di-Hydroxy Allantoinate"],
    functions: ["soothing_support", "skin_conditioning"],
    commonUses: ["comfort support", "barrier routine support"],
    suitableFor: ["dry", "sensitive", "redness"],
    cautionFor: ["known sensitivity to the product formula"],
    avoidWith: [],
    evidenceLevel: "basic",
    sourceRefs: ["manual-curation"],
  },
  {
    inciName: "Zinc Oxide",
    aliases: ["Mineral UV Filter"],
    functions: ["uv_filter", "skin_protective"],
    commonUses: ["mineral sunscreen filter", "daytime routine support"],
    suitableFor: ["sensitive", "redness", "dark_spots"],
    cautionFor: ["users who dislike white cast or heavier texture"],
    avoidWith: [],
    evidenceLevel: "strong",
    sourceRefs: ["manual-curation"],
  },
  {
    inciName: "Avobenzone",
    aliases: ["Butyl Methoxydibenzoylmethane"],
    functions: ["uv_filter"],
    commonUses: ["UVA sunscreen filter", "daytime routine support"],
    suitableFor: ["normal", "combination", "dark_spots"],
    cautionFor: ["known sensitivity to chemical UV filters"],
    avoidWith: [],
    evidenceLevel: "strong",
    sourceRefs: ["manual-curation"],
  },
  {
    inciName: "Bis-Ethylhexyloxyphenol Methoxyphenyl Triazine",
    aliases: ["Tinosorb S", "BEMT"],
    functions: ["uv_filter"],
    commonUses: ["broad-spectrum sunscreen filter", "daytime routine support"],
    suitableFor: ["normal", "combination", "dark_spots"],
    cautionFor: ["known sensitivity to sunscreen formulas"],
    avoidWith: [],
    evidenceLevel: "strong",
    sourceRefs: ["manual-curation"],
  },
  {
    inciName: "Fragrance",
    aliases: ["Parfum", "Perfume"],
    functions: ["fragrance_component"],
    commonUses: ["scent"],
    suitableFor: ["users who tolerate fragranced products"],
    cautionFor: ["sensitive skin", "redness-prone skin", "fragrance sensitivity"],
    avoidWith: ["recently irritated skin"],
    evidenceLevel: "uncertain",
    sourceRefs: ["manual-curation"],
  },
  {
    inciName: "Alcohol Denat.",
    aliases: ["Denatured Alcohol"],
    functions: ["solvent", "texture_support"],
    commonUses: ["quick-dry texture", "lightweight finish"],
    suitableFor: ["oily skin that tolerates drying formulas"],
    cautionFor: ["dry skin", "sensitive skin", "recently irritated skin"],
    avoidWith: ["over-exfoliated skin"],
    evidenceLevel: "uncertain",
    sourceRefs: ["manual-curation"],
  },
  {
    inciName: "Menthol",
    aliases: ["Mentha component"],
    functions: ["fragrance_component", "sensory_agent"],
    commonUses: ["cooling feel", "scent"],
    suitableFor: ["users who tolerate cooling fragranced products"],
    cautionFor: ["sensitive skin", "redness-prone skin", "recently irritated skin"],
    avoidWith: ["strong exfoliant routines", "retinoid routines"],
    evidenceLevel: "uncertain",
    sourceRefs: ["manual-curation"],
  },
  {
    inciName: "Dimethicone",
    aliases: ["Silicone"],
    functions: ["emollient", "occlusive", "texture_support"],
    commonUses: ["smooth texture", "barrier-supporting moisturizer feel"],
    suitableFor: ["dry", "normal", "sensitive", "barrier_support"],
    cautionFor: ["users who dislike silicone texture"],
    avoidWith: [],
    evidenceLevel: "basic",
    sourceRefs: ["manual-curation"],
  },
  {
    inciName: "Shea Butter",
    aliases: ["Butyrospermum Parkii Butter"],
    functions: ["emollient", "occlusive"],
    commonUses: ["rich moisturizer support", "dryness support"],
    suitableFor: ["dry", "normal", "barrier_support"],
    cautionFor: ["very oily skin", "users who dislike rich textures"],
    avoidWith: [],
    evidenceLevel: "basic",
    sourceRefs: ["manual-curation"],
  },
  {
    inciName: "Petrolatum",
    aliases: ["Petroleum Jelly"],
    functions: ["occlusive", "barrier_support"],
    commonUses: ["small-area dryness support", "last-step occlusive support"],
    suitableFor: ["dry", "sensitive", "barrier_support"],
    cautionFor: ["very oily skin", "users who dislike heavy textures"],
    avoidWith: [],
    evidenceLevel: "strong",
    sourceRefs: ["manual-curation"],
  },
  {
    inciName: "Ceramide AP",
    aliases: ["Ceramide AP lipid"],
    functions: ["barrier_support", "emollient"],
    commonUses: ["barrier support", "moisturizer support"],
    suitableFor: ["dry", "sensitive", "barrier_support"],
    cautionFor: ["known sensitivity to the product formula"],
    avoidWith: [],
    evidenceLevel: "moderate",
    sourceRefs: ["manual-curation"],
  },
  {
    inciName: "Ceramide EOP",
    aliases: ["Ceramide EOP lipid"],
    functions: ["barrier_support", "emollient"],
    commonUses: ["barrier support", "rich moisturizer support"],
    suitableFor: ["dry", "sensitive", "barrier_support"],
    cautionFor: ["known sensitivity to the product formula"],
    avoidWith: [],
    evidenceLevel: "moderate",
    sourceRefs: ["manual-curation"],
  },
  {
    inciName: "Beta-Glucan",
    aliases: ["Beta Glucan"],
    functions: ["soothing_support", "hydration_support", "barrier_support"],
    commonUses: ["comfort support", "hydration support"],
    suitableFor: ["dry", "sensitive", "redness", "barrier_support"],
    cautionFor: ["known sensitivity to the product formula"],
    avoidWith: [],
    evidenceLevel: "basic",
    sourceRefs: ["manual-curation"],
  },
  {
    inciName: "Trehalose",
    aliases: ["Trehalose humectant"],
    functions: ["humectant", "hydration_support"],
    commonUses: ["hydration support", "lightweight serum support"],
    suitableFor: ["dry", "normal", "combination", "sensitive"],
    cautionFor: ["known sensitivity to the product formula"],
    avoidWith: [],
    evidenceLevel: "basic",
    sourceRefs: ["manual-curation"],
  },
  {
    inciName: "Aloe Barbadensis Leaf Juice",
    aliases: ["Aloe Vera"],
    functions: ["soothing_support", "hydration_support", "botanical_extract"],
    commonUses: ["comfort support", "light hydration support"],
    suitableFor: ["normal", "combination", "sensitive", "redness"],
    cautionFor: ["known sensitivity to aloe or botanical extracts"],
    avoidWith: [],
    evidenceLevel: "basic",
    sourceRefs: ["manual-curation"],
  },
  {
    inciName: "Bisabolol",
    aliases: ["Alpha-Bisabolol"],
    functions: ["soothing_support", "skin_conditioning"],
    commonUses: ["comfort support", "redness-prone routine support"],
    suitableFor: ["dry", "sensitive", "redness"],
    cautionFor: ["known sensitivity to the product formula"],
    avoidWith: [],
    evidenceLevel: "basic",
    sourceRefs: ["manual-curation"],
  },
  {
    inciName: "Oat Extract",
    aliases: ["Avena Sativa Kernel Extract"],
    functions: ["soothing_support", "skin_conditioning"],
    commonUses: ["comfort support", "barrier routine support"],
    suitableFor: ["dry", "sensitive", "redness", "barrier_support"],
    cautionFor: ["known sensitivity to oat-derived ingredients"],
    avoidWith: [],
    evidenceLevel: "basic",
    sourceRefs: ["manual-curation"],
  },
  {
    inciName: "Kojic Acid",
    aliases: ["Kojic Acid Dipalmitate"],
    functions: ["tone_support", "active"],
    commonUses: ["uneven tone support", "dark-spot routine support"],
    suitableFor: ["normal", "combination", "dark_spots"],
    cautionFor: ["sensitive skin", "recently irritated skin"],
    avoidWith: ["too many strong actives in one routine"],
    evidenceLevel: "basic",
    sourceRefs: ["manual-curation"],
  },
  {
    inciName: "Sodium Ascorbyl Phosphate",
    aliases: ["SAP", "Vitamin C derivative"],
    functions: ["antioxidant", "tone_support", "active"],
    commonUses: ["antioxidant support", "tone support"],
    suitableFor: ["oily", "combination", "normal", "dark_spots"],
    cautionFor: ["very sensitive skin", "recently irritated skin"],
    avoidWith: ["too many strong actives in one routine"],
    evidenceLevel: "basic",
    sourceRefs: ["manual-curation"],
  },
  {
    inciName: "Titanium Dioxide",
    aliases: ["Titanium Dioxide UV Filter"],
    functions: ["uv_filter", "skin_protective"],
    commonUses: ["mineral sunscreen filter", "daytime routine support"],
    suitableFor: ["sensitive", "redness", "dark_spots"],
    cautionFor: ["users who dislike white cast or thicker textures"],
    avoidWith: [],
    evidenceLevel: "strong",
    sourceRefs: ["manual-curation"],
  },
  {
    inciName: "Diethylamino Hydroxybenzoyl Hexyl Benzoate",
    aliases: ["Uvinul A Plus", "DHHB"],
    functions: ["uv_filter"],
    commonUses: ["UVA sunscreen filter", "daytime routine support"],
    suitableFor: ["normal", "combination", "dark_spots"],
    cautionFor: ["known sensitivity to sunscreen formulas"],
    avoidWith: [],
    evidenceLevel: "strong",
    sourceRefs: ["manual-curation"],
  },
  {
    inciName: "Octocrylene",
    aliases: ["Octocrylene UV Filter"],
    functions: ["uv_filter"],
    commonUses: ["sunscreen filter support", "daytime routine support"],
    suitableFor: ["normal", "combination", "oily", "dark_spots"],
    cautionFor: ["known sensitivity to chemical UV filters"],
    avoidWith: [],
    evidenceLevel: "strong",
    sourceRefs: ["manual-curation"],
  },
  {
    inciName: "Tea Tree Oil",
    aliases: ["Melaleuca Alternifolia Leaf Oil"],
    functions: ["fragrance_component", "botanical_extract", "oil_balance"],
    commonUses: ["oiliness-prone routine support", "scent"],
    suitableFor: ["oily skin that tolerates essential oils"],
    cautionFor: ["sensitive skin", "redness-prone skin", "recently irritated skin"],
    avoidWith: ["strong exfoliant routines", "retinoid routines"],
    evidenceLevel: "uncertain",
    sourceRefs: ["manual-curation"],
  },
  {
    inciName: "Ferulic Acid",
    aliases: ["Ferulic antioxidant"],
    functions: ["antioxidant", "active"],
    commonUses: ["antioxidant support", "vitamin C formula support"],
    suitableFor: ["normal", "combination", "dark_spots"],
    cautionFor: ["very sensitive skin", "recently irritated skin"],
    avoidWith: ["too many strong actives in one routine"],
    evidenceLevel: "basic",
    sourceRefs: ["manual-curation"],
  },
  {
    inciName: "Tocopherol",
    aliases: ["Vitamin E"],
    functions: ["antioxidant", "skin_conditioning"],
    commonUses: ["antioxidant support", "moisturizer support"],
    suitableFor: ["dry", "normal", "combination", "barrier_support"],
    cautionFor: ["known sensitivity to the product formula"],
    avoidWith: [],
    evidenceLevel: "basic",
    sourceRefs: ["manual-curation"],
  },
  {
    inciName: "Caffeine",
    aliases: ["Caffeine skin-conditioning agent"],
    functions: ["skin_conditioning", "antioxidant"],
    commonUses: ["lightweight serum support", "refreshing eye-area formula support"],
    suitableFor: ["normal", "combination", "oiliness"],
    cautionFor: ["known sensitivity to the product formula"],
    avoidWith: [],
    evidenceLevel: "basic",
    sourceRefs: ["manual-curation"],
  },
  {
    inciName: "Kaolin",
    aliases: ["White Clay"],
    functions: ["absorbent", "texture_support"],
    commonUses: ["oiliness-prone mask support", "rinse-off clay formula support"],
    suitableFor: ["oily", "combination", "oiliness"],
    cautionFor: ["dry skin", "sensitive skin", "recently irritated skin"],
    avoidWith: ["over-exfoliated skin"],
    evidenceLevel: "basic",
    sourceRefs: ["manual-curation"],
  },
  {
    inciName: "Caprylic/Capric Triglyceride",
    aliases: ["CCT emollient"],
    functions: ["emollient", "texture_support"],
    commonUses: ["lightweight moisturizer support", "soft skin feel"],
    suitableFor: ["dry", "normal", "combination", "barrier_support"],
    cautionFor: ["users who dislike richer emollient textures"],
    avoidWith: [],
    evidenceLevel: "basic",
    sourceRefs: ["manual-curation"],
  },
  {
    inciName: "Palmitoyl Tripeptide-1",
    aliases: ["Signal peptide"],
    functions: ["skin_conditioning", "texture_support"],
    commonUses: ["texture support", "moisturizer or serum support"],
    suitableFor: ["dry", "normal", "combination", "texture"],
    cautionFor: ["known sensitivity to the product formula"],
    avoidWith: [],
    evidenceLevel: "basic",
    sourceRefs: ["manual-curation"],
  },
  {
    inciName: "Lactobionic Acid",
    aliases: ["Bionic acid PHA"],
    functions: ["exfoliant", "humectant", "texture_support", "active"],
    commonUses: ["gentle PHA-style texture support", "hydrating exfoliant support"],
    suitableFor: ["dry", "sensitive", "texture", "barrier_support"],
    cautionFor: ["recently irritated skin", "over-exfoliated skin", "very sensitive routines"],
    avoidWith: ["same-routine retinoids", "too many exfoliating acids"],
    evidenceLevel: "moderate",
    sourceRefs: ["manual-curation"],
  },
  {
    inciName: "Polyglutamic Acid",
    aliases: ["PGA humectant"],
    functions: ["humectant", "hydration_support", "skin_conditioning"],
    commonUses: ["hydrating serum support", "moisture-retention formula support"],
    suitableFor: ["dry", "normal", "combination", "barrier_support"],
    cautionFor: ["known sensitivity to the product formula"],
    avoidWith: [],
    evidenceLevel: "basic",
    sourceRefs: ["manual-curation"],
  },
  {
    inciName: "Ectoin",
    aliases: ["Ectoine"],
    functions: ["barrier_support", "skin_conditioning", "soothing"],
    commonUses: ["sensitive routine support", "barrier-support serum or cream support"],
    suitableFor: ["dry", "sensitive", "redness", "barrier_support"],
    cautionFor: ["known sensitivity to the product formula"],
    avoidWith: [],
    evidenceLevel: "basic",
    sourceRefs: ["manual-curation"],
  },
  {
    inciName: "Acetyl Glucosamine",
    aliases: ["N-Acetyl Glucosamine", "NAG"],
    functions: ["tone_support", "humectant", "skin_conditioning"],
    commonUses: ["tone-support serum support", "hydrating brightening-style formula support"],
    suitableFor: ["normal", "combination", "dry", "dark_spots", "texture"],
    cautionFor: ["known sensitivity to the product formula"],
    avoidWith: [],
    evidenceLevel: "basic",
    sourceRefs: ["manual-curation"],
  },
  {
    inciName: "Rice Bran Extract",
    aliases: ["Oryza Sativa Bran Extract"],
    functions: ["antioxidant", "botanical_extract", "skin_conditioning"],
    commonUses: ["antioxidant serum support", "soft tone-support formula support"],
    suitableFor: ["normal", "dry", "combination", "dark_spots", "barrier_support"],
    cautionFor: ["known sensitivity to botanical extracts"],
    avoidWith: [],
    evidenceLevel: "basic",
    sourceRefs: ["manual-curation"],
  },
  {
    inciName: "Chamomile Extract",
    aliases: ["Chamomilla Recutita Flower Extract"],
    functions: ["soothing", "botanical_extract", "skin_conditioning"],
    commonUses: ["redness-prone routine support", "rinse-off or leave-on comfort support"],
    suitableFor: ["dry", "sensitive", "redness", "barrier_support"],
    cautionFor: ["known sensitivity to botanical extracts"],
    avoidWith: [],
    evidenceLevel: "basic",
    sourceRefs: ["manual-curation"],
  },
  {
    inciName: "Colloidal Oatmeal",
    aliases: ["Avena Sativa Kernel Flour"],
    functions: ["soothing", "barrier_support", "skin_conditioning"],
    commonUses: ["comfort mask support", "dry-feeling routine support"],
    suitableFor: ["dry", "sensitive", "redness", "barrier_support"],
    cautionFor: ["known oat sensitivity"],
    avoidWith: [],
    evidenceLevel: "basic",
    sourceRefs: ["manual-curation"],
  },
  {
    inciName: "Isoamyl Laurate",
    aliases: ["Lightweight ester"],
    functions: ["emollient", "texture_support"],
    commonUses: ["lightweight moisturizer support", "sunscreen texture support"],
    suitableFor: ["normal", "combination", "oily", "texture"],
    cautionFor: ["known sensitivity to the product formula"],
    avoidWith: [],
    evidenceLevel: "basic",
    sourceRefs: ["manual-curation"],
  },
  {
    inciName: "Cetearyl Alcohol",
    aliases: ["Fatty alcohol"],
    functions: ["emollient", "texture_support", "barrier_support"],
    commonUses: ["cream texture support", "moisturizer structure support"],
    suitableFor: ["dry", "normal", "sensitive", "barrier_support"],
    cautionFor: ["users who dislike richer cream textures"],
    avoidWith: [],
    evidenceLevel: "basic",
    sourceRefs: ["manual-curation"],
  },
  {
    inciName: "Polyquaternium-51",
    aliases: ["Lipidure"],
    functions: ["humectant", "skin_conditioning", "barrier_support"],
    commonUses: ["hydrating serum support", "comfort-focused moisturizer support"],
    suitableFor: ["dry", "normal", "sensitive", "barrier_support"],
    cautionFor: ["known sensitivity to the product formula"],
    avoidWith: [],
    evidenceLevel: "basic",
    sourceRefs: ["manual-curation"],
  },
  {
    inciName: "Butylene Glycol",
    aliases: ["Butylene Glycol humectant"],
    functions: ["humectant", "solvent", "skin_conditioning"],
    commonUses: ["hydrating formula support", "lightweight serum texture support"],
    suitableFor: ["oily", "dry", "normal", "combination"],
    cautionFor: ["known sensitivity to the product formula"],
    avoidWith: [],
    evidenceLevel: "basic",
    sourceRefs: ["manual-curation"],
  },
] satisfies IngredientSeed[];

const productSeeds = [
  {
    name: "Gentle Low pH Cleanser",
    brand: "SkinWise Demo",
    category: "cleanser",
    priceRange: "budget",
    ingredientsText: "Water, Cocamidopropyl Betaine, Glycerin, Panthenol",
    keyActives: ["Panthenol"],
    tags: ["gentle", "low-ph", "basic-routine", "oily-skin-friendly"],
    warnings: [],
    skinTypes: ["oily", "normal", "combination", "sensitive"],
    concerns: ["acne", "oiliness", "dryness", "barrier_support"],
    suitableFor: [
      "basic morning cleanse",
      "basic evening cleanse",
      "beginner oily or combination routine",
    ],
    notRecommendedFor: ["known sensitivity to listed surfactants"],
    source: "manual",
    verificationStatus: "verified",
  },
  {
    name: "Creamy Non-Stripping Cleanser",
    brand: "SkinWise Demo",
    category: "cleanser",
    priceRange: "mid",
    ingredientsText: "Water, Glycerin, Mild Surfactant Blend, Ceramide NP",
    keyActives: ["Ceramide NP", "Glycerin"],
    tags: ["cream-cleanser", "barrier-support"],
    warnings: [],
    skinTypes: ["dry", "normal", "sensitive"],
    concerns: ["dryness", "barrier_support", "redness"],
    suitableFor: ["dry-feeling skin", "minimal evening routine"],
    notRecommendedFor: ["users who prefer foaming cleansers"],
    source: "manual",
    verificationStatus: "reviewed",
  },
  {
    name: "Barrier Repair Moisturizer",
    brand: "SkinWise Demo",
    category: "moisturizer",
    priceRange: "mid",
    ingredientsText: "Water, Glycerin, Ceramide NP, Panthenol, Squalane",
    keyActives: ["Ceramide NP", "Panthenol"],
    tags: ["barrier-support", "fragrance-free", "lightweight-gel-cream"],
    warnings: [],
    skinTypes: ["oily", "dry", "normal", "combination", "sensitive"],
    concerns: ["dryness", "redness", "barrier_support", "oiliness"],
    suitableFor: [
      "basic routine support",
      "skin that feels tight",
      "lightweight moisturizer step for oily or combination routines",
    ],
    notRecommendedFor: ["known sensitivity to listed emollients"],
    source: "manual",
    verificationStatus: "verified",
  },
  {
    name: "Centella Recovery Cream",
    brand: "SkinWise Demo",
    category: "moisturizer",
    priceRange: "mid",
    ingredientsText: "Water, Centella Asiatica Extract, Glycerin, Panthenol",
    keyActives: ["Centella Asiatica Extract", "Panthenol"],
    tags: ["cica", "soothing-support"],
    warnings: ["Botanical extracts can still bother some sensitive skin."],
    skinTypes: ["normal", "combination", "sensitive"],
    concerns: ["redness", "barrier_support"],
    suitableFor: ["comfort-focused routine", "simple recovery routine"],
    notRecommendedFor: ["known sensitivity to botanical extracts"],
    source: "manual",
    verificationStatus: "reviewed",
  },
  {
    name: "Daily Lightweight Sunscreen SPF50",
    brand: "SkinWise Demo",
    category: "sunscreen",
    priceRange: "mid",
    ingredientsText: "Water, UV Filters, Glycerin, Niacinamide",
    keyActives: ["UV Filters", "Niacinamide"],
    tags: ["sunscreen", "morning-routine", "lightweight"],
    warnings: ["Reapply according to product label, especially with sun exposure."],
    skinTypes: ["oily", "combination", "normal"],
    concerns: ["dark_spots", "oiliness"],
    suitableFor: ["morning routine", "daytime routine planning"],
    notRecommendedFor: ["known sensitivity to listed UV filters"],
    source: "manual",
    verificationStatus: "verified",
  },
  {
    name: "Mineral Comfort Sunscreen SPF50",
    brand: "SkinWise Demo",
    category: "sunscreen",
    priceRange: "premium",
    ingredientsText: "Water, Zinc Oxide, Glycerin, Panthenol",
    keyActives: ["Zinc Oxide", "Panthenol"],
    tags: ["sunscreen", "mineral", "sensitive-skin"],
    warnings: ["May leave a visible cast depending on skin tone and amount used."],
    skinTypes: ["dry", "normal", "sensitive"],
    concerns: ["redness", "barrier_support", "dark_spots"],
    suitableFor: ["sensitive morning routine", "daily sun protection step"],
    notRecommendedFor: ["users avoiding mineral sunscreen texture"],
    source: "manual",
    verificationStatus: "reviewed",
  },
  {
    name: "Niacinamide 5% Serum",
    brand: "SkinWise Demo",
    category: "serum",
    priceRange: "budget",
    ingredientsText: "Water, Niacinamide, Zinc PCA, Panthenol",
    keyActives: ["Niacinamide", "Zinc PCA", "Panthenol"],
    tags: ["oiliness-support", "barrier-support", "beginner-active"],
    warnings: ["Introduce gradually if your skin is easily irritated."],
    skinTypes: ["oily", "combination", "normal"],
    concerns: ["acne", "oiliness", "dark_spots", "barrier_support", "texture"],
    suitableFor: [
      "simple oiliness support",
      "beginner serum step",
      "post-acne tone support in a simple routine",
    ],
    notRecommendedFor: ["currently irritated skin"],
    source: "manual",
    verificationStatus: "verified",
  },
  {
    name: "Hydrating Hyaluronic Acid Serum",
    brand: "SkinWise Demo",
    category: "serum",
    priceRange: "budget",
    ingredientsText: "Water, Glycerin, Hyaluronic Acid, Panthenol",
    keyActives: ["Hyaluronic Acid", "Panthenol"],
    tags: ["hydrating", "humectant", "basic-routine"],
    warnings: [],
    skinTypes: ["dry", "normal", "combination", "sensitive"],
    concerns: ["dryness", "barrier_support"],
    suitableFor: ["hydration support under moisturizer"],
    notRecommendedFor: ["users who prefer moisturizer-only routines"],
    source: "manual",
    verificationStatus: "verified",
  },
  {
    name: "Vitamin C Antioxidant Serum",
    brand: "SkinWise Demo",
    category: "serum",
    priceRange: "premium",
    ingredientsText: "Water, Vitamin C, Ferulic Acid, Glycerin",
    keyActives: ["Vitamin C", "Ferulic Acid"],
    tags: ["antioxidant", "morning-routine"],
    warnings: ["Can tingle or irritate sensitive skin; patch test first."],
    skinTypes: ["normal", "combination", "oily"],
    concerns: ["dark_spots", "texture"],
    suitableFor: ["experienced users adding one morning active"],
    notRecommendedFor: ["very sensitive or currently irritated skin"],
    source: "manual",
    verificationStatus: "reviewed",
  },
  {
    name: "Azelaic Acid 10% Cream",
    brand: "SkinWise Demo",
    category: "treatment",
    priceRange: "mid",
    ingredientsText: "Water, Azelaic Acid, Glycerin, Dimethicone",
    keyActives: ["Azelaic Acid"],
    tags: ["tone-support", "redness-support"],
    warnings: ["May sting at first; avoid layering with too many actives."],
    skinTypes: ["oily", "combination", "normal"],
    concerns: ["acne", "redness", "dark_spots", "texture"],
    suitableFor: [
      "single-active evening routine",
      "post-acne mark support without adding multiple strong actives",
    ],
    notRecommendedFor: ["freshly irritated or compromised skin"],
    source: "manual",
    verificationStatus: "verified",
  },
  {
    name: "BHA 2% Exfoliant",
    brand: "SkinWise Demo",
    category: "treatment",
    priceRange: "mid",
    ingredientsText: "Water, Salicylic Acid, Glycerin, Green Tea Extract",
    keyActives: ["Salicylic Acid", "Green Tea Extract"],
    tags: ["bha", "exfoliant", "weekly-use", "pore-support"],
    warnings: ["Avoid overuse and avoid combining with retinoids in one routine."],
    skinTypes: ["oily", "combination"],
    concerns: ["acne", "oiliness", "dark_spots", "texture"],
    suitableFor: [
      "occasional exfoliation step",
      "clogged-pore support for non-irritated oily skin",
    ],
    notRecommendedFor: ["sensitive, dry, or over-exfoliated skin"],
    source: "manual",
    verificationStatus: "reviewed",
  },
  {
    name: "Retinol 0.2% Night Serum",
    brand: "SkinWise Demo",
    category: "treatment",
    priceRange: "mid",
    ingredientsText: "Water, Retinol, Glycerin, Peptide Complex",
    keyActives: ["Retinol", "Peptide Complex"],
    tags: ["retinoid", "night-routine", "advanced-active"],
    warnings: ["Introduce slowly; avoid same-routine AHA/BHA combinations."],
    skinTypes: ["normal", "combination"],
    concerns: ["texture"],
    suitableFor: ["experienced evening routine users"],
    notRecommendedFor: ["pregnancy or breastfeeding without professional guidance"],
    source: "manual",
    verificationStatus: "reviewed",
  },
  {
    name: "Benzoyl Peroxide Spot Treatment",
    brand: "SkinWise Demo",
    category: "treatment",
    priceRange: "budget",
    ingredientsText: "Water, Benzoyl Peroxide, Glycerin",
    keyActives: ["Benzoyl Peroxide"],
    tags: ["spot-care", "blemish-support"],
    warnings: ["Can feel drying; avoid layering with retinoids in one routine."],
    skinTypes: ["oily", "combination"],
    concerns: ["acne", "oiliness"],
    suitableFor: ["limited spot-care use as directed by product label"],
    notRecommendedFor: ["sensitive or very dry skin"],
    source: "manual",
    verificationStatus: "reviewed",
  },
  {
    name: "Gentle Hydrating Toner",
    brand: "SkinWise Demo",
    category: "toner",
    priceRange: "budget",
    ingredientsText: "Water, Glycerin, Panthenol, Hyaluronic Acid",
    keyActives: ["Panthenol", "Hyaluronic Acid"],
    tags: ["hydrating", "optional-step", "soothing-support"],
    warnings: [],
    skinTypes: ["dry", "normal", "combination", "sensitive"],
    concerns: ["dryness", "redness", "barrier_support"],
    suitableFor: ["optional hydration layer", "soothing toner step"],
    notRecommendedFor: ["users keeping routines very minimal"],
    source: "manual",
    verificationStatus: "verified",
  },
  {
    name: "Basic Occlusive Balm",
    brand: "SkinWise Demo",
    category: "other",
    priceRange: "budget",
    ingredientsText: "Petrolatum, Mineral Oil, Panthenol",
    keyActives: ["Panthenol"],
    tags: ["occlusive", "dryness-support", "minimal-routine"],
    warnings: ["Can feel heavy or occlusive for oily skin."],
    skinTypes: ["dry", "normal", "sensitive"],
    concerns: ["dryness", "barrier_support"],
    suitableFor: ["small-area dryness support", "last step over moisturizer"],
    notRecommendedFor: ["very oily skin or dislike of heavy textures"],
    source: "manual",
    verificationStatus: "reviewed",
  },
  {
    name: "ClearLeaf Gentle Low pH Cleanser",
    brand: "ClearLeaf Lab",
    category: "cleanser",
    priceRange: "budget",
    ingredientsText: "Water, Cocamidopropyl Betaine, Glycerin, Panthenol, Allantoin",
    keyActives: ["Glycerin", "Panthenol", "Allantoin"],
    tags: ["gentle", "low-ph", "fragrance-free", "basic-routine"],
    warnings: ["Patch test if your skin is currently reactive or recently irritated."],
    skinTypes: ["normal", "combination", "sensitive"],
    concerns: ["dryness", "redness", "barrier_support"],
    suitableFor: ["basic morning cleanse", "basic evening cleanse", "sensitive routine foundation"],
    notRecommendedFor: ["known sensitivity to listed surfactants"],
    source: "manual",
    verificationStatus: "verified",
  },
  {
    name: "FreshPlain Oil Balance Gel Cleanser",
    brand: "FreshPlain",
    category: "cleanser",
    priceRange: "mid",
    ingredientsText: "Water, Sodium Cocoyl Glutamate, Glycerin, Zinc PCA, Green Tea Extract",
    keyActives: ["Zinc PCA", "Green Tea Extract"],
    tags: ["gel-cleanser", "oiliness-support", "fragrance-free"],
    warnings: ["Avoid over-cleansing even when skin feels oily."],
    skinTypes: ["oily", "combination", "normal"],
    concerns: ["oiliness", "acne", "texture"],
    suitableFor: ["oily morning routine", "lightweight evening cleanse"],
    notRecommendedFor: ["very dry or recently irritated skin"],
    source: "manual",
    verificationStatus: "reviewed",
  },
  {
    name: "AquaMild Betaine Hydration Toner",
    brand: "AquaMild",
    category: "toner",
    priceRange: "budget",
    ingredientsText: "Water, Glycerin, Betaine, Sodium PCA, Panthenol",
    keyActives: ["Betaine", "Sodium PCA", "Panthenol"],
    tags: ["hydrating", "fragrance-free", "optional-step"],
    warnings: ["Optional step; moisturizer is still useful for sealing hydration."],
    skinTypes: ["dry", "normal", "combination", "sensitive"],
    concerns: ["dryness", "barrier_support", "redness"],
    suitableFor: ["hydration layer under moisturizer", "simple recovery routine"],
    notRecommendedFor: ["users who prefer very minimal routines"],
    source: "manual",
    verificationStatus: "verified",
  },
  {
    name: "FreshPlain Cooling Botanical Toner",
    brand: "FreshPlain",
    category: "toner",
    priceRange: "mid",
    ingredientsText: "Water, Glycerin, Green Tea Extract, Fragrance, Menthol",
    keyActives: ["Green Tea Extract", "Fragrance", "Menthol"],
    tags: ["botanical", "fragranced", "cooling-feel"],
    warnings: ["Contains Fragrance and Menthol; use with caution if skin is sensitive or recently irritated."],
    skinTypes: ["oily", "combination"],
    concerns: ["oiliness", "redness"],
    suitableFor: ["users who tolerate fragranced lightweight toners"],
    notRecommendedFor: ["sensitive skin", "redness-prone skin", "recently irritated skin"],
    source: "manual",
    verificationStatus: "reviewed",
  },
  {
    name: "AquaMild Hyaluronic Hydration Serum",
    brand: "AquaMild",
    category: "serum",
    priceRange: "budget",
    ingredientsText: "Water, Glycerin, Hyaluronic Acid, Sodium PCA, Panthenol",
    keyActives: ["Hyaluronic Acid", "Sodium PCA", "Panthenol"],
    tags: ["hydrating", "humectant", "fragrance-free"],
    warnings: ["Use with moisturizer if your skin feels dry after humectant layers."],
    skinTypes: ["dry", "normal", "combination", "sensitive"],
    concerns: ["dryness", "barrier_support"],
    suitableFor: ["hydration support under moisturizer", "beginner serum step"],
    notRecommendedFor: ["users who prefer moisturizer-only routines"],
    source: "manual",
    verificationStatus: "verified",
  },
  {
    name: "GlowBase Azelaic Tone Support Serum",
    brand: "GlowBase",
    category: "serum",
    priceRange: "mid",
    ingredientsText: "Water, Azelaic Acid, Niacinamide, Glycerin, Dimethicone",
    keyActives: ["Azelaic Acid", "Niacinamide"],
    tags: ["tone-support", "redness-support", "single-active"],
    warnings: ["May sting on recently irritated skin; introduce slowly."],
    skinTypes: ["oily", "combination", "normal"],
    concerns: ["dark_spots", "redness", "texture", "acne"],
    suitableFor: ["single-active evening routine", "uneven tone support"],
    notRecommendedFor: ["freshly irritated or over-exfoliated skin"],
    source: "manual",
    verificationStatus: "verified",
  },
  {
    name: "GlowBase Tranexamic Bright Tone Serum",
    brand: "GlowBase",
    category: "serum",
    priceRange: "premium",
    ingredientsText: "Water, Tranexamic Acid, Alpha Arbutin, Licorice Root Extract, Glycerin",
    keyActives: ["Tranexamic Acid", "Alpha Arbutin", "Licorice Root Extract"],
    tags: ["tone-support", "dark-spot-support", "fragrance-free"],
    warnings: ["Use sunscreen in the morning when working on uneven tone concerns."],
    skinTypes: ["normal", "combination", "dry"],
    concerns: ["dark_spots", "texture", "barrier_support"],
    suitableFor: ["uneven tone support", "routine with consistent sunscreen"],
    notRecommendedFor: ["currently irritated skin"],
    source: "manual",
    verificationStatus: "reviewed",
  },
  {
    name: "SkinKind L-Ascorbic Antioxidant Serum",
    brand: "SkinKind Lab",
    category: "serum",
    priceRange: "premium",
    ingredientsText: "Water, L Ascorbic Acid, Ferulic Acid, Glycerin",
    keyActives: ["L Ascorbic Acid", "Vitamin C"],
    tags: ["antioxidant", "morning-routine", "strong-active"],
    warnings: ["Can tingle; avoid stacking with too many strong actives if skin is sensitive."],
    skinTypes: ["normal", "combination", "oily"],
    concerns: ["dark_spots", "texture"],
    suitableFor: ["experienced users adding one morning antioxidant active"],
    notRecommendedFor: ["very sensitive or recently irritated skin"],
    source: "manual",
    verificationStatus: "reviewed",
  },
  {
    name: "ClearBalance Zinc PCA Oil Serum",
    brand: "ClearBalance",
    category: "serum",
    priceRange: "budget",
    ingredientsText: "Water, Niacinamide, Zinc PCA, Green Tea Extract, Panthenol",
    keyActives: ["Niacinamide", "Zinc PCA", "Green Tea Extract"],
    tags: ["oiliness-support", "lightweight", "fragrance-free"],
    warnings: ["Introduce gradually if your skin reacts easily to active serums."],
    skinTypes: ["oily", "combination"],
    concerns: ["oiliness", "acne", "barrier_support"],
    suitableFor: ["lightweight oiliness support", "beginner-friendly serum routine"],
    notRecommendedFor: ["currently irritated skin"],
    source: "manual",
    verificationStatus: "verified",
  },
  {
    name: "CicaTheory Madecassoside Comfort Serum",
    brand: "CicaTheory",
    category: "serum",
    priceRange: "mid",
    ingredientsText: "Water, Centella Asiatica Extract, Madecassoside, Allantoin, Glycerin",
    keyActives: ["Centella Asiatica Extract", "Madecassoside", "Allantoin"],
    tags: ["cica", "soothing-support", "fragrance-free"],
    warnings: ["Botanical extracts can still bother some users; patch test first."],
    skinTypes: ["sensitive", "dry", "normal", "combination"],
    concerns: ["redness", "dryness", "barrier_support"],
    suitableFor: ["comfort-focused routine", "barrier recovery routine"],
    notRecommendedFor: ["known sensitivity to botanical extracts"],
    source: "manual",
    verificationStatus: "verified",
  },
  {
    name: "CalmBarrier Ceramide Recovery Cream",
    brand: "CalmBarrier",
    category: "moisturizer",
    priceRange: "mid",
    ingredientsText: "Water, Glycerin, Ceramide NP, Cholesterol, Fatty Acids, Panthenol",
    keyActives: ["Ceramide NP", "Cholesterol", "Fatty Acids", "Panthenol"],
    tags: ["barrier-support", "fragrance-free", "recovery-cream"],
    warnings: ["Rich textures may feel heavy for very oily skin."],
    skinTypes: ["dry", "normal", "sensitive"],
    concerns: ["dryness", "redness", "barrier_support"],
    suitableFor: ["barrier recovery routine", "dry or tight-feeling skin"],
    notRecommendedFor: ["very oily skin that dislikes rich creams"],
    source: "manual",
    verificationStatus: "verified",
  },
  {
    name: "DermaPlain Fragrance-Free Barrier Lotion",
    brand: "DermaPlain",
    category: "moisturizer",
    priceRange: "budget",
    ingredientsText: "Water, Glycerin, Squalane, Dimethicone, Allantoin",
    keyActives: ["Squalane", "Dimethicone", "Allantoin"],
    tags: ["fragrance-free", "barrier-support", "lotion"],
    warnings: ["Patch test if you are sensitive to silicone textures."],
    skinTypes: ["normal", "combination", "sensitive"],
    concerns: ["dryness", "redness", "barrier_support"],
    suitableFor: ["daily moisturizer step", "simple sensitive-skin routine"],
    notRecommendedFor: ["known sensitivity to silicone textures"],
    source: "manual",
    verificationStatus: "verified",
  },
  {
    name: "BarrierNest Panthenol Repair Balm",
    brand: "BarrierNest",
    category: "moisturizer",
    priceRange: "premium",
    ingredientsText: "Water, Petrolatum, Shea Butter, Panthenol, Ceramide NP",
    keyActives: ["Panthenol", "Ceramide NP", "Petrolatum"],
    tags: ["rich-balm", "dryness-support", "barrier-support"],
    warnings: ["Can feel heavy; use a thin layer or small-area application if preferred."],
    skinTypes: ["dry", "sensitive"],
    concerns: ["dryness", "barrier_support", "redness"],
    suitableFor: ["night routine for dry-feeling skin", "small-area dryness support"],
    notRecommendedFor: ["very oily skin or dislike of occlusive textures"],
    source: "manual",
    verificationStatus: "reviewed",
  },
  {
    name: "SunNest Mineral Comfort Sunscreen SPF50",
    brand: "SunNest",
    category: "sunscreen",
    priceRange: "mid",
    ingredientsText: "Water, Zinc Oxide, Titanium Dioxide, Glycerin, Panthenol",
    keyActives: ["Zinc Oxide", "Titanium Dioxide", "Panthenol"],
    tags: ["sunscreen", "mineral", "fragrance-free", "morning-routine"],
    warnings: ["May leave a visible cast depending on amount used and skin tone."],
    skinTypes: ["sensitive", "dry", "normal"],
    concerns: ["dark_spots", "redness", "barrier_support"],
    suitableFor: ["morning routine", "sensitive daytime routine"],
    notRecommendedFor: ["users avoiding mineral sunscreen texture"],
    source: "manual",
    verificationStatus: "verified",
  },
  {
    name: "DailyKind Lightweight Sunscreen SPF50",
    brand: "DailyKind",
    category: "sunscreen",
    priceRange: "budget",
    ingredientsText: "Water, Avobenzone, Tinosorb S, Glycerin, Niacinamide",
    keyActives: ["Avobenzone", "Tinosorb S", "Niacinamide"],
    tags: ["sunscreen", "lightweight", "morning-routine"],
    warnings: ["Reapply according to the product label, especially with sun exposure."],
    skinTypes: ["oily", "combination", "normal"],
    concerns: ["dark_spots", "oiliness"],
    suitableFor: ["daily morning routine", "lightweight sunscreen step"],
    notRecommendedFor: ["known sensitivity to listed UV filters"],
    source: "manual",
    verificationStatus: "verified",
  },
  {
    name: "SoftRoutine Dew Sunscreen SPF50",
    brand: "SoftRoutine",
    category: "sunscreen",
    priceRange: "mid",
    ingredientsText: "Water, Tinosorb S, Glycerin, Squalane, Hyaluronic Acid",
    keyActives: ["Tinosorb S", "Hyaluronic Acid", "Squalane"],
    tags: ["sunscreen", "dewy-finish", "dryness-support"],
    warnings: ["Dewy finish may feel shiny for very oily skin."],
    skinTypes: ["dry", "normal", "combination"],
    concerns: ["dark_spots", "dryness", "barrier_support"],
    suitableFor: ["morning routine for dry-feeling skin"],
    notRecommendedFor: ["very oily skin that dislikes dewy finishes"],
    source: "manual",
    verificationStatus: "reviewed",
  },
  {
    name: "BalanceLab Matte Day Sunscreen SPF50",
    brand: "BalanceLab",
    category: "sunscreen",
    priceRange: "premium",
    ingredientsText: "Water, Avobenzone, Tinosorb S, Alcohol Denat., Zinc PCA",
    keyActives: ["Avobenzone", "Tinosorb S", "Zinc PCA", "Alcohol Denat."],
    tags: ["sunscreen", "matte-finish", "oiliness-support"],
    warnings: ["Contains Alcohol Denat.; use with caution if skin is dry, sensitive, or recently irritated."],
    skinTypes: ["oily", "combination"],
    concerns: ["oiliness", "dark_spots"],
    suitableFor: ["matte morning routine for oilier skin"],
    notRecommendedFor: ["dry skin", "sensitive skin", "recently irritated skin"],
    source: "manual",
    verificationStatus: "reviewed",
  },
  {
    name: "MildTheory Mandelic PHA Resurfacing Liquid",
    brand: "MildTheory",
    category: "treatment",
    priceRange: "mid",
    ingredientsText: "Water, Mandelic Acid, Gluconolactone, Glycerin, Panthenol",
    keyActives: ["Mandelic Acid", "PHA", "Gluconolactone"],
    tags: ["aha", "pha", "exfoliant", "weekly-use"],
    warnings: ["Avoid overuse and avoid combining with retinoids or other exfoliants in the same routine."],
    skinTypes: ["normal", "combination", "dry"],
    concerns: ["texture", "dark_spots", "dryness"],
    suitableFor: ["occasional exfoliation support", "experienced users using sunscreen consistently"],
    notRecommendedFor: ["sensitive, over-exfoliated, or recently irritated skin"],
    source: "manual",
    verificationStatus: "reviewed",
  },
  {
    name: "ClearBalance BHA Pore Support Liquid",
    brand: "ClearBalance",
    category: "treatment",
    priceRange: "budget",
    ingredientsText: "Water, Salicylic Acid, BHA, Green Tea Extract, Glycerin",
    keyActives: ["Salicylic Acid", "BHA"],
    tags: ["bha", "exfoliant", "pore-support", "weekly-use"],
    warnings: ["Avoid same-routine retinoids and avoid overuse, especially if skin is sensitive."],
    skinTypes: ["oily", "combination"],
    concerns: ["acne", "oiliness", "texture"],
    suitableFor: ["occasional clogged-pore support", "simple routine with moisturizer"],
    notRecommendedFor: ["dry, sensitive, or over-exfoliated skin"],
    source: "manual",
    verificationStatus: "verified",
  },
  {
    name: "RoutineBase Retinal Night Support",
    brand: "RoutineBase",
    category: "treatment",
    priceRange: "premium",
    ingredientsText: "Water, Retinal, Glycerin, Palmitoyl Tripeptide-1",
    keyActives: ["Retinal", "Palmitoyl Tripeptide-1", "Glycerin"],
    tags: ["retinoid", "night-routine", "advanced-active"],
    warnings: ["Introduce slowly; avoid same-routine AHA/BHA products and use daytime sunscreen."],
    skinTypes: ["normal", "combination"],
    concerns: ["texture", "dark_spots"],
    suitableFor: ["experienced evening routine users"],
    notRecommendedFor: ["beginners", "sensitive skin", "pregnancy or breastfeeding without professional guidance"],
    source: "manual",
    verificationStatus: "reviewed",
  },
  {
    name: "DewKind Urea Squalane Comfort Lotion",
    brand: "DewKind",
    category: "moisturizer",
    priceRange: "mid",
    ingredientsText: "Water, Glycerin, Urea, Squalane, Dimethicone, Panthenol",
    keyActives: ["Urea", "Squalane", "Panthenol"],
    tags: ["comfort-lotion", "dryness-support", "barrier-support"],
    warnings: ["Urea can sting on cracked or recently irritated skin; patch test first."],
    skinTypes: ["dry", "normal", "combination"],
    concerns: ["dryness", "texture", "barrier_support"],
    suitableFor: ["dryness support", "rough-feeling texture support", "simple evening moisturizer"],
    notRecommendedFor: ["currently cracked, stinging, or recently irritated skin"],
    source: "manual",
    verificationStatus: "reviewed",
  },
  {
    name: "PureCica Recovery Gel Mask",
    brand: "PureCica",
    category: "mask",
    priceRange: "mid",
    ingredientsText: "Water, Centella Asiatica Extract, Madecassoside, Panthenol, Allantoin",
    keyActives: ["Centella Asiatica Extract", "Madecassoside", "Panthenol"],
    tags: ["mask", "cica", "soothing-support", "fragrance-free"],
    warnings: ["Use as an optional support step; do not replace moisturizer if skin feels dry."],
    skinTypes: ["sensitive", "dry", "normal", "combination"],
    concerns: ["redness", "dryness", "barrier_support"],
    suitableFor: ["comfort-focused weekly routine", "post-active rest night"],
    notRecommendedFor: ["known sensitivity to botanical extracts"],
    source: "manual",
    verificationStatus: "verified",
  },
  {
    name: "CicaNest Aromatic Clay Mask",
    brand: "CicaNest",
    category: "mask",
    priceRange: "mid",
    ingredientsText: "Water, Kaolin, Green Tea Extract, Parfum, Essential Oil Blend",
    keyActives: ["Green Tea Extract", "Parfum", "Essential Oil Blend"],
    tags: ["mask", "clay", "fragranced"],
    warnings: ["Contains Parfum and Essential Oil Blend; use with caution if skin is sensitive or redness-prone."],
    skinTypes: ["oily", "combination", "unknown"],
    concerns: ["oiliness", "unknown"],
    suitableFor: ["users who tolerate fragranced clay masks"],
    notRecommendedFor: ["sensitive skin", "redness-prone skin", "recently irritated skin"],
    source: "manual",
    verificationStatus: "reviewed",
  },
  {
    name: "OatCloud Milk Cleanser",
    brand: "OatCloud",
    category: "cleanser",
    priceRange: "mid",
    ingredientsText: "Water, Glycerin, Oat Extract, Beta-Glucan, Mild Surfactant Blend",
    keyActives: ["Oat Extract", "Beta-Glucan", "Glycerin"],
    tags: ["cream-cleanser", "fragrance-free", "sensitive-skin"],
    warnings: ["Patch test first if you are sensitive to oat-derived ingredients."],
    skinTypes: ["dry", "normal", "sensitive"],
    concerns: ["dryness", "redness", "barrier_support"],
    suitableFor: ["gentle evening cleanse", "dry or sensitive routine foundation"],
    notRecommendedFor: ["known sensitivity to oat-derived ingredients"],
    source: "manual",
    verificationStatus: "verified",
  },
  {
    name: "ClearBalance BHA Gel Cleanser",
    brand: "ClearBalance",
    category: "cleanser",
    priceRange: "budget",
    ingredientsText: "Water, Mild Surfactant Blend, Salicylic Acid, Glycerin, Zinc PCA",
    keyActives: ["Salicylic Acid", "Zinc PCA"],
    tags: ["gel-cleanser", "bha", "oiliness-support"],
    warnings: ["Contains Salicylic Acid; avoid over-cleansing and patch test first."],
    skinTypes: ["oily", "combination"],
    concerns: ["acne", "oiliness", "texture"],
    suitableFor: ["oily evening cleanse", "simple blemish-prone routine support"],
    notRecommendedFor: ["dry, sensitive, or recently irritated skin"],
    source: "manual",
    verificationStatus: "reviewed",
  },
  {
    name: "CalmBarrier Oat Beta-Glucan Cream",
    brand: "CalmBarrier",
    category: "moisturizer",
    priceRange: "mid",
    ingredientsText: "Water, Glycerin, Beta-Glucan, Oat Extract, Ceramide NP, Squalane",
    keyActives: ["Beta-Glucan", "Oat Extract", "Ceramide NP"],
    tags: ["barrier-support", "fragrance-free", "comfort-cream"],
    warnings: ["Patch test first if you are sensitive to oat-derived ingredients."],
    skinTypes: ["dry", "normal", "sensitive"],
    concerns: ["dryness", "redness", "barrier_support"],
    suitableFor: ["barrier support routine", "redness-prone comfort routine"],
    notRecommendedFor: ["known sensitivity to oat-derived ingredients"],
    source: "manual",
    verificationStatus: "verified",
  },
  {
    name: "LipidKind Ceramide Triple Lotion",
    brand: "LipidKind",
    category: "moisturizer",
    priceRange: "premium",
    ingredientsText: "Water, Glycerin, Ceramide NP, Ceramide AP, Ceramide EOP, Cholesterol, Fatty Acids",
    keyActives: ["Ceramide NP", "Ceramide AP", "Ceramide EOP", "Cholesterol"],
    tags: ["barrier-support", "fragrance-free", "lipid-lotion"],
    warnings: ["Rich lipid textures may feel heavy for very oily skin."],
    skinTypes: ["dry", "normal", "sensitive"],
    concerns: ["dryness", "barrier_support", "redness"],
    suitableFor: ["dry barrier support routine", "simple evening moisturizer"],
    notRecommendedFor: ["very oily skin that dislikes richer textures"],
    source: "manual",
    verificationStatus: "verified",
  },
  {
    name: "AloeCica Water Gel Moisturizer",
    brand: "AloeCica",
    category: "moisturizer",
    priceRange: "budget",
    ingredientsText: "Water, Aloe Barbadensis Leaf Juice, Centella Asiatica Extract, Glycerin, Panthenol",
    keyActives: ["Aloe Barbadensis Leaf Juice", "Centella Asiatica Extract", "Panthenol"],
    tags: ["gel-moisturizer", "soothing-support", "lightweight"],
    warnings: ["Botanical extracts can bother some users; patch test first."],
    skinTypes: ["oily", "combination", "normal", "sensitive"],
    concerns: ["redness", "oiliness", "barrier_support"],
    suitableFor: ["lightweight moisturizer step", "redness-prone routine support"],
    notRecommendedFor: ["known sensitivity to aloe or botanical extracts"],
    source: "manual",
    verificationStatus: "reviewed",
  },
  {
    name: "SimpleStep Basic Moisture Gel",
    brand: "SimpleStep",
    category: "moisturizer",
    priceRange: "budget",
    ingredientsText: "Water, Glycerin, Trehalose, Sodium PCA, Dimethicone",
    keyActives: ["Glycerin", "Trehalose", "Sodium PCA"],
    tags: ["minimal-routine", "lightweight", "fragrance-free"],
    warnings: ["Patch test first if your skin is currently reactive."],
    skinTypes: ["oily", "combination", "normal", "unknown"],
    concerns: ["dryness", "barrier_support", "unknown"],
    suitableFor: ["minimal routine moisturizer", "beginner basic routine"],
    notRecommendedFor: ["users who need a richer cream texture"],
    source: "manual",
    verificationStatus: "verified",
  },
  {
    name: "SunNest Sensitive Mineral Fluid SPF50",
    brand: "SunNest",
    category: "sunscreen",
    priceRange: "premium",
    ingredientsText: "Water, Zinc Oxide, Titanium Dioxide, Glycerin, Bisabolol",
    keyActives: ["Zinc Oxide", "Titanium Dioxide", "Bisabolol"],
    tags: ["sunscreen", "mineral", "sensitive-skin", "fragrance-free"],
    warnings: ["May leave a visible cast depending on amount used and skin tone."],
    skinTypes: ["sensitive", "dry", "normal"],
    concerns: ["redness", "dark_spots", "barrier_support"],
    suitableFor: ["sensitive morning routine", "daily sunscreen step"],
    notRecommendedFor: ["users avoiding mineral sunscreen texture"],
    source: "manual",
    verificationStatus: "verified",
  },
  {
    name: "DailyKind Aqua UV Gel SPF50",
    brand: "DailyKind",
    category: "sunscreen",
    priceRange: "mid",
    ingredientsText: "Water, Diethylamino Hydroxybenzoyl Hexyl Benzoate, Octocrylene, Glycerin, Trehalose",
    keyActives: ["DHHB", "Octocrylene", "Trehalose"],
    tags: ["sunscreen", "lightweight", "gel-texture", "morning-routine"],
    warnings: ["Patch test first if you are sensitive to chemical UV filters."],
    skinTypes: ["oily", "combination", "normal"],
    concerns: ["dark_spots", "oiliness", "texture"],
    suitableFor: ["lightweight daily sunscreen", "oily or combination morning routine"],
    notRecommendedFor: ["known sensitivity to chemical UV filters"],
    source: "manual",
    verificationStatus: "verified",
  },
  {
    name: "BarrierSun Cream Sunscreen SPF50",
    brand: "BarrierSun",
    category: "sunscreen",
    priceRange: "mid",
    ingredientsText: "Water, Tinosorb S, DHHB, Glycerin, Ceramide AP, Panthenol",
    keyActives: ["Tinosorb S", "DHHB", "Ceramide AP", "Panthenol"],
    tags: ["sunscreen", "barrier-support", "cream-texture"],
    warnings: ["Cream finish may feel rich for very oily skin."],
    skinTypes: ["dry", "normal", "sensitive"],
    concerns: ["dark_spots", "dryness", "barrier_support"],
    suitableFor: ["dry morning routine", "sunscreen step with comfort support"],
    notRecommendedFor: ["very oily skin that dislikes cream sunscreen"],
    source: "manual",
    verificationStatus: "reviewed",
  },
  {
    name: "TonePath SAP Licorice Serum",
    brand: "TonePath",
    category: "serum",
    priceRange: "mid",
    ingredientsText: "Water, Sodium Ascorbyl Phosphate, Licorice Root Extract, Glycerin, Panthenol",
    keyActives: ["Sodium Ascorbyl Phosphate", "Licorice Root Extract"],
    tags: ["tone-support", "vitamin-c-derivative", "fragrance-free"],
    warnings: ["Introduce gradually and use sunscreen consistently in the morning."],
    skinTypes: ["oily", "combination", "normal", "sensitive"],
    concerns: ["dark_spots", "redness", "texture"],
    suitableFor: ["gentler tone-support routine", "morning or evening serum step"],
    notRecommendedFor: ["currently irritated skin"],
    source: "manual",
    verificationStatus: "verified",
  },
  {
    name: "SpotSoft Kojic Licorice Serum",
    brand: "SpotSoft",
    category: "serum",
    priceRange: "premium",
    ingredientsText: "Water, Kojic Acid, Licorice Root Extract, Niacinamide, Glycerin",
    keyActives: ["Kojic Acid", "Licorice Root Extract", "Niacinamide"],
    tags: ["tone-support", "dark-spot-support", "strong-active"],
    warnings: ["Kojic Acid may irritate sensitive skin; introduce slowly and patch test first."],
    skinTypes: ["normal", "combination", "oily"],
    concerns: ["dark_spots", "texture"],
    suitableFor: ["experienced tone-support routine", "routine with daily sunscreen"],
    notRecommendedFor: ["sensitive, over-exfoliated, or recently irritated skin"],
    source: "manual",
    verificationStatus: "reviewed",
  },
  {
    name: "AquaMild Trehalose Hydration Ampoule",
    brand: "AquaMild",
    category: "serum",
    priceRange: "budget",
    ingredientsText: "Water, Trehalose, Sodium PCA, Hyaluronic Acid, Glycerin",
    keyActives: ["Trehalose", "Sodium PCA", "Hyaluronic Acid"],
    tags: ["hydrating", "humectant", "fragrance-free"],
    warnings: ["Use with moisturizer if skin feels dry after humectant layers."],
    skinTypes: ["dry", "normal", "combination", "sensitive"],
    concerns: ["dryness", "barrier_support"],
    suitableFor: ["hydration support under moisturizer", "minimal routine serum"],
    notRecommendedFor: ["users who prefer moisturizer-only routines"],
    source: "manual",
    verificationStatus: "verified",
  },
  {
    name: "PeptideNest Barrier Support Serum",
    brand: "PeptideNest",
    category: "serum",
    priceRange: "premium",
    ingredientsText: "Water, Palmitoyl Tripeptide-1, Panthenol, Glycerin, Ceramide NP",
    keyActives: ["Palmitoyl Tripeptide-1", "Panthenol", "Ceramide NP"],
    tags: ["barrier-support", "texture-support", "fragrance-free"],
    warnings: ["Patch test first if your skin is currently reactive."],
    skinTypes: ["dry", "normal", "combination", "sensitive"],
    concerns: ["barrier_support", "dryness", "texture"],
    suitableFor: ["barrier support serum step", "texture support without exfoliation"],
    notRecommendedFor: ["known sensitivity to peptide formulas"],
    source: "manual",
    verificationStatus: "reviewed",
  },
  {
    name: "MildTheory PHA Comfort Toner",
    brand: "MildTheory",
    category: "toner",
    priceRange: "mid",
    ingredientsText: "Water, Gluconolactone, Panthenol, Beta-Glucan, Glycerin",
    keyActives: ["Gluconolactone", "Panthenol", "Beta-Glucan"],
    tags: ["pha", "gentle-exfoliant", "hydrating"],
    warnings: ["Avoid overuse and avoid stacking with other exfoliants in the same routine."],
    skinTypes: ["dry", "normal", "combination", "sensitive"],
    concerns: ["texture", "dryness", "barrier_support"],
    suitableFor: ["occasional mild texture support", "hydrating toner step"],
    notRecommendedFor: ["recently irritated or over-exfoliated skin"],
    source: "manual",
    verificationStatus: "reviewed",
  },
  {
    name: "OatCloud Aloe Mist Toner",
    brand: "OatCloud",
    category: "toner",
    priceRange: "budget",
    ingredientsText: "Water, Aloe Barbadensis Leaf Juice, Oat Extract, Trehalose, Glycerin",
    keyActives: ["Aloe Barbadensis Leaf Juice", "Oat Extract", "Trehalose"],
    tags: ["hydrating", "soothing-support", "fragrance-free"],
    warnings: ["Patch test first if you are sensitive to aloe or oat-derived ingredients."],
    skinTypes: ["dry", "normal", "combination", "sensitive"],
    concerns: ["dryness", "redness", "barrier_support"],
    suitableFor: ["optional hydration mist", "sensitive routine support"],
    notRecommendedFor: ["known sensitivity to aloe or oat-derived ingredients"],
    source: "manual",
    verificationStatus: "verified",
  },
  {
    name: "ClayKind Sulfur Clarifying Mask",
    brand: "ClayKind",
    category: "mask",
    priceRange: "mid",
    ingredientsText: "Water, Kaolin, Sulfur, Zinc PCA, Glycerin",
    keyActives: ["Sulfur", "Zinc PCA", "Kaolin"],
    tags: ["mask", "oiliness-support", "rinse-off", "strong-active"],
    warnings: ["Sulfur and clay can feel drying; limit frequency and patch test first."],
    skinTypes: ["oily", "combination"],
    concerns: ["acne", "oiliness", "texture"],
    suitableFor: ["occasional rinse-off mask for oily routines"],
    notRecommendedFor: ["dry, sensitive, or recently irritated skin"],
    source: "manual",
    verificationStatus: "reviewed",
  },
  {
    name: "CalmSleep Barrier Sleeping Mask",
    brand: "CalmSleep",
    category: "mask",
    priceRange: "premium",
    ingredientsText: "Water, Glycerin, Squalane, Ceramide EOP, Panthenol, Beta-Glucan",
    keyActives: ["Squalane", "Ceramide EOP", "Panthenol", "Beta-Glucan"],
    tags: ["sleeping-mask", "barrier-support", "fragrance-free"],
    warnings: ["Richer texture may feel heavy for very oily skin."],
    skinTypes: ["dry", "normal", "sensitive"],
    concerns: ["dryness", "redness", "barrier_support"],
    suitableFor: ["post-active rest night", "dry-feeling evening routine"],
    notRecommendedFor: ["very oily skin that dislikes rich textures"],
    source: "manual",
    verificationStatus: "verified",
  },
  {
    name: "ClearLeaf Tea Tree Spot Gel",
    brand: "ClearLeaf Lab",
    category: "treatment",
    priceRange: "budget",
    ingredientsText: "Water, Tea Tree Oil, Zinc PCA, Panthenol, Glycerin",
    keyActives: ["Tea Tree Oil", "Zinc PCA"],
    tags: ["spot-care", "essential-oil", "oiliness-support"],
    warnings: ["Tea Tree Oil can irritate sensitive skin; use sparingly and patch test first."],
    skinTypes: ["oily", "combination"],
    concerns: ["acne", "oiliness"],
    suitableFor: ["limited spot-care use for users who tolerate essential oils"],
    notRecommendedFor: ["sensitive skin", "redness-prone skin", "recently irritated skin"],
    source: "manual",
    verificationStatus: "reviewed",
  },
  {
    name: "MildTheory Lactic PHA Texture Lotion",
    brand: "MildTheory",
    category: "treatment",
    priceRange: "mid",
    ingredientsText: "Water, Lactic Acid, Gluconolactone, Glycerin, Panthenol",
    keyActives: ["Lactic Acid", "Gluconolactone"],
    tags: ["aha", "pha", "texture-support", "weekly-use"],
    warnings: ["Avoid overuse and avoid same-routine retinoids or other exfoliants."],
    skinTypes: ["dry", "normal", "combination"],
    concerns: ["texture", "dryness", "dark_spots"],
    suitableFor: ["occasional texture support", "experienced users using sunscreen consistently"],
    notRecommendedFor: ["sensitive, over-exfoliated, or recently irritated skin"],
    source: "manual",
    verificationStatus: "reviewed",
  },
  {
    name: "RoutineBase Minimal Routine Set",
    brand: "RoutineBase",
    category: "other",
    priceRange: "unknown",
    ingredientsText: "Low pH cleanser, simple moisturizer, daily sunscreen planning card",
    keyActives: ["Glycerin", "Panthenol", "Sunscreen"],
    tags: ["minimal-routine", "beginner-routine", "education-support"],
    warnings: ["Use the set as planning support; check each product label before use."],
    skinTypes: ["unknown", "normal", "combination"],
    concerns: ["unknown", "dryness", "barrier_support"],
    suitableFor: ["beginner minimal routine planning", "demo account routine walkthrough"],
    notRecommendedFor: ["users who need a personalized product review before choosing items"],
    source: "manual",
    verificationStatus: "reviewed",
  },
  {
    name: "PoreKind Amino Gel Cleanser",
    brand: "PoreKind",
    category: "cleanser",
    priceRange: "budget",
    ingredientsText: "Water, Amino Acid Surfactant Blend, Glycerin, Butylene Glycol, Zinc PCA",
    keyActives: ["Glycerin", "Butylene Glycol", "Zinc PCA"],
    tags: ["gel-cleanser", "oiliness-support", "fragrance-free"],
    warnings: [],
    skinTypes: ["oily", "combination", "normal"],
    concerns: ["acne", "oiliness", "texture"],
    suitableFor: ["oily or combination morning cleanse", "lightweight beginner routine"],
    notRecommendedFor: ["known sensitivity to listed surfactants"],
    source: "manual",
    verificationStatus: "verified",
  },
  {
    name: "MildTheory Lactobionic PHA Toner",
    brand: "MildTheory",
    category: "toner",
    priceRange: "mid",
    ingredientsText: "Water, Lactobionic Acid, Polyglutamic Acid, Panthenol, Glycerin",
    keyActives: ["Lactobionic Acid", "Polyglutamic Acid", "Panthenol"],
    tags: ["pha", "gentle-exfoliant", "hydrating-toner"],
    warnings: ["Avoid overuse and avoid same-routine retinoids or other exfoliants."],
    skinTypes: ["dry", "normal", "combination", "sensitive"],
    concerns: ["texture", "dryness", "barrier_support"],
    suitableFor: ["occasional texture support", "dry-feeling routine with sunscreen habits"],
    notRecommendedFor: ["over-exfoliated or recently irritated skin"],
    source: "manual",
    verificationStatus: "reviewed",
  },
  {
    name: "DewKind Polyglutamic Hydration Serum",
    brand: "DewKind",
    category: "serum",
    priceRange: "mid",
    ingredientsText: "Water, Polyglutamic Acid, Glycerin, Sodium PCA, Butylene Glycol",
    keyActives: ["Polyglutamic Acid", "Glycerin", "Sodium PCA"],
    tags: ["hydrating-serum", "humectant", "fragrance-free"],
    warnings: [],
    skinTypes: ["dry", "normal", "combination", "sensitive"],
    concerns: ["dryness", "barrier_support", "redness"],
    suitableFor: ["dehydrated-feeling routine support", "lightweight barrier-support layering"],
    notRecommendedFor: ["users who dislike humectant serum textures"],
    source: "manual",
    verificationStatus: "verified",
  },
  {
    name: "EctoinCalm Barrier Serum",
    brand: "EctoinCalm",
    category: "serum",
    priceRange: "premium",
    ingredientsText: "Water, Ectoin, Beta-Glucan, Panthenol, Ceramide NP",
    keyActives: ["Ectoin", "Beta-Glucan", "Panthenol", "Ceramide NP"],
    tags: ["barrier-support", "soothing", "fragrance-free"],
    warnings: [],
    skinTypes: ["dry", "normal", "combination", "sensitive"],
    concerns: ["redness", "barrier_support", "dryness"],
    suitableFor: ["sensitive-feeling routine support", "post-active rest night"],
    notRecommendedFor: ["known sensitivity to the product formula"],
    source: "manual",
    verificationStatus: "verified",
  },
  {
    name: "GlowBase NAG Rice Tone Serum",
    brand: "GlowBase",
    category: "serum",
    priceRange: "mid",
    ingredientsText: "Water, Acetyl Glucosamine, Rice Bran Extract, Niacinamide, Glycerin",
    keyActives: ["Acetyl Glucosamine", "Rice Bran Extract", "Niacinamide"],
    tags: ["tone-support", "antioxidant", "hydrating-serum"],
    warnings: ["Introduce gradually if already using multiple tone-support actives."],
    skinTypes: ["normal", "combination", "dry"],
    concerns: ["dark_spots", "texture", "barrier_support"],
    suitableFor: ["dullness-style demo routines using dark spot or texture concerns"],
    notRecommendedFor: ["known sensitivity to niacinamide or botanical extracts"],
    source: "manual",
    verificationStatus: "reviewed",
  },
  {
    name: "SunNest Matte Oil Control SPF50",
    brand: "SunNest",
    category: "sunscreen",
    priceRange: "mid",
    ingredientsText: "Water, Zinc Oxide, DHHB, Isoamyl Laurate, Silica, Glycerin",
    keyActives: ["Zinc Oxide", "DHHB", "Isoamyl Laurate"],
    tags: ["sunscreen", "matte-finish", "oiliness-support"],
    warnings: ["Reapply as directed on the product label during daytime exposure."],
    skinTypes: ["oily", "combination", "normal"],
    concerns: ["oiliness", "dark_spots", "texture"],
    suitableFor: ["normal to oily daytime routine", "sunscreen-focused demo routine"],
    notRecommendedFor: ["users who dislike matte sunscreen textures"],
    source: "manual",
    verificationStatus: "reviewed",
  },
  {
    name: "DailyKind Dew Shield SPF50",
    brand: "DailyKind",
    category: "sunscreen",
    priceRange: "mid",
    ingredientsText: "Water, Tinosorb S, DHHB, Glycerin, Polyglutamic Acid, Panthenol",
    keyActives: ["Tinosorb S", "DHHB", "Polyglutamic Acid"],
    tags: ["sunscreen", "hydrating", "daily-routine"],
    warnings: ["Reapply as directed on the product label during daytime exposure."],
    skinTypes: ["dry", "normal", "sensitive"],
    concerns: ["dryness", "dark_spots", "barrier_support"],
    suitableFor: ["dry or normal daytime routine", "simple sunscreen support"],
    notRecommendedFor: ["known sensitivity to sunscreen filters"],
    source: "manual",
    verificationStatus: "reviewed",
  },
  {
    name: "OatCloud Colloidal Oat Comfort Mask",
    brand: "OatCloud",
    category: "mask",
    priceRange: "mid",
    ingredientsText: "Water, Colloidal Oatmeal, Beta-Glucan, Chamomile Extract, Glycerin",
    keyActives: ["Colloidal Oatmeal", "Beta-Glucan", "Chamomile Extract"],
    tags: ["comfort-mask", "barrier-support", "soothing"],
    warnings: ["Patch test first if sensitive to oat or botanical ingredients."],
    skinTypes: ["dry", "normal", "combination", "sensitive"],
    concerns: ["redness", "dryness", "barrier_support"],
    suitableFor: ["post-active rest routine", "dry or sensitive-feeling demo routine"],
    notRecommendedFor: ["known oat or botanical sensitivity"],
    source: "manual",
    verificationStatus: "verified",
  },
  {
    name: "ClearBalance Sulfur BHA Spot Lotion",
    brand: "ClearBalance",
    category: "treatment",
    priceRange: "budget",
    ingredientsText: "Water, Sulfur, Salicylic Acid, Zinc PCA, Panthenol",
    keyActives: ["Sulfur", "Salicylic Acid", "Zinc PCA"],
    tags: ["spot-care", "bha", "oiliness-support"],
    warnings: ["Can feel drying; avoid layering with retinoids or other exfoliants in the same routine."],
    skinTypes: ["oily", "combination"],
    concerns: ["acne", "oiliness", "texture"],
    suitableFor: ["limited spot-care use in oily or combination demo routines"],
    notRecommendedFor: ["dry, sensitive, over-exfoliated, or recently irritated skin"],
    source: "manual",
    verificationStatus: "reviewed",
  },
  {
    name: "RoutineBase Ectoin Night Cream",
    brand: "RoutineBase",
    category: "moisturizer",
    priceRange: "premium",
    ingredientsText: "Water, Ectoin, Ceramide NP, Cetearyl Alcohol, Squalane, Panthenol",
    keyActives: ["Ectoin", "Ceramide NP", "Squalane", "Panthenol"],
    tags: ["night-cream", "barrier-support", "fragrance-free"],
    warnings: ["Richer texture may feel heavy for very oily skin."],
    skinTypes: ["dry", "normal", "sensitive"],
    concerns: ["barrier_support", "dryness", "redness"],
    suitableFor: ["dry-feeling evening routine", "post-active rest night"],
    notRecommendedFor: ["very oily skin that dislikes rich textures"],
    source: "manual",
    verificationStatus: "verified",
  },
  {
    name: "LipidKind Fatty Acid Soft Cream",
    brand: "LipidKind",
    category: "moisturizer",
    priceRange: "premium",
    ingredientsText: "Water, Fatty Acids, Cetearyl Alcohol, Isoamyl Laurate, Cholesterol, Glycerin",
    keyActives: ["Fatty Acids", "Cetearyl Alcohol", "Cholesterol", "Glycerin"],
    tags: ["soft-cream", "barrier-support", "emollient"],
    warnings: ["Richer emollient feel may not suit users who prefer gel textures."],
    skinTypes: ["dry", "normal", "sensitive"],
    concerns: ["dryness", "barrier_support", "texture"],
    suitableFor: ["barrier-support demo routines", "dry or sensitive-feeling skin profiles"],
    notRecommendedFor: ["very oily skin that dislikes cream textures"],
    source: "manual",
    verificationStatus: "verified",
  },
  {
    name: "RoutineBase Patch Test Planning Cards",
    brand: "RoutineBase",
    category: "other",
    priceRange: "unknown",
    ingredientsText: "Patch test guide card, routine spacing checklist, sunscreen reminder",
    keyActives: ["Sunscreen", "Patch test reminder"],
    tags: ["education-support", "routine-planning", "demo-support"],
    warnings: ["Planning cards are educational support and do not replace checking each product label."],
    skinTypes: ["unknown", "normal", "sensitive"],
    concerns: ["unknown", "barrier_support", "redness"],
    suitableFor: ["portfolio demo routine planning", "beginner product spacing walkthrough"],
    notRecommendedFor: ["users who need a personalized product review before choosing items"],
    source: "manual",
    verificationStatus: "reviewed",
  },
] satisfies ProductSeed[];

function requireMongoUriFromProcess() {
  const uri = process.env.MONGODB_URI;

  if (!uri) {
    throw new Error("MONGODB_URI is required before running db:seed.");
  }

  if (!uri.startsWith("mongodb://") && !uri.startsWith("mongodb+srv://")) {
    throw new Error("MONGODB_URI must start with mongodb:// or mongodb+srv://.");
  }
}

function summarizeWriteResult(result: BulkWriteResult): SeedWriteSummary {
  return {
    matchedCount: result.matchedCount,
    modifiedCount: result.modifiedCount,
    upsertedCount: result.upsertedCount,
  };
}

async function seedIngredients(
  collection: Collection<IngredientDocument>,
  ingredients: IngredientSeed[],
) {
  const now = new Date();
  const result = await collection.bulkWrite(
    ingredients.map((ingredient) => ({
      updateOne: {
        filter: {
          inciName: ingredient.inciName,
        },
        update: {
          $set: {
            ...ingredient,
            updatedAt: now,
          },
          $setOnInsert: {
            createdAt: now,
          },
        },
        upsert: true,
      },
    })),
    { ordered: true },
  );

  return summarizeWriteResult(result);
}

async function seedProducts(
  collection: Collection<ProductDocument>,
  products: ProductSeed[],
) {
  const now = new Date();
  const result = await collection.bulkWrite(
    products.map((product) => ({
      updateOne: {
        filter: {
          brand: product.brand,
          name: product.name,
          source: MANUAL_PRODUCT_SOURCE,
        },
        update: {
          $set: {
            ...product,
            updatedAt: now,
          },
          $setOnInsert: {
            createdAt: now,
          },
        },
        upsert: true,
      },
    })),
    { ordered: true },
  );

  return summarizeWriteResult(result);
}

function printSummary(
  databaseName: string,
  ingredients: SeedWriteSummary,
  products: SeedWriteSummary,
) {
  console.info(`db:seed connected database: ${databaseName}`);
  console.info(`ingredients matched: ${ingredients.matchedCount}`);
  console.info(`ingredients inserted/upserted: ${ingredients.upsertedCount}`);
  console.info(`ingredients modified: ${ingredients.modifiedCount}`);
  console.info(`products matched: ${products.matchedCount}`);
  console.info(`products inserted/upserted: ${products.upsertedCount}`);
  console.info(`products modified: ${products.modifiedCount}`);
}

export async function main() {
  const seedData = validateSeedData();

  requireMongoUriFromProcess();

  const [{ getMongoClient, getMongoDb }, collections] = await Promise.all([
    import("@/infrastructure/database/mongodb"),
    import("@/infrastructure/database/collections"),
  ]);
  const client = await getMongoClient();

  try {
    const db = await getMongoDb();
    const [ingredientsCollection, productsCollection] = await Promise.all([
      collections.getIngredientsCollection<IngredientDocument>(),
      collections.getProductsCollection<ProductDocument>(),
    ]);
    const [ingredientSummary, productSummary] = await Promise.all([
      seedIngredients(ingredientsCollection, seedData.ingredients),
      seedProducts(productsCollection, seedData.products),
    ]);

    printSummary(db.databaseName, ingredientSummary, productSummary);
  } finally {
    await client.close();
  }
}

function isDirectInvocation() {
  const invokedPath = process.argv[1];

  return Boolean(
    invokedPath && import.meta.url === pathToFileURL(invokedPath).href,
  );
}

if (isDirectInvocation()) {
  main().catch((error: unknown) => {
    console.error("db:seed failed");

    if (error instanceof z.ZodError) {
      for (const issue of error.issues) {
        console.error(`${issue.path.join(".")}: ${issue.message}`);
      }
    } else {
      console.error(error instanceof Error ? error.message : "Unknown error");
    }

    process.exitCode = 1;
  });
}
